version: '3.8'
services:
  app:
    build: .
    image: dickynhf/sit323_737-2024-t1-prac5p-node-web
    ports:
      - '3043:3040'
    environment:
      - PORT=3043
    container_name: my-app4
    networks:
      - my-net

  app1:
    build: .
    image: dickynhf/sit323_737-2024-t1-prac5p-node-web
    ports:
      - '3044:3040'
    environment:
      - PORT=3044
    container_name: my-app3
    networks:
      - my-net


networks:
  my-net:
    driver: bridge